### ISSUE TITLE
auth0.v3.exceptions.Auth0Error: 400: You are not allowed to use search_engine=v1.

### ISSUE THREAD

**Issue by d33tah** [auth0/auth0-python#183]
### Description

I'm trying to list users using this library. Here's my interactive session:

```
[00:04:42]>>> auth0.users.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/users.py", line 69, in list
    return self.client.get(self._url(), params=params)
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 52, in get
    return self._process_response(response)
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 86, in _process_response
    return self._parse(response).content()
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 106, in content
    message=self._error_message())
auth0.v3.exceptions.Auth0Error: 400: You are not allowed to use search_engine=v1.
```

I'm surprised to find v3 in the error message and search_engine=v1 in the error message.

### Prerequisites

- [x] I have checked the [README documentation](https://github.com/auth0/auth0-python/blob/master/README.rst).
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-python/issues) and [PRs](https://github.com/auth0/auth0-python/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository.

### Environment

Please provide the following:

- Version of the library being used: `auth0-python==3.6.1`
- Relevant environmental versions (language version, OS version): Ubuntu 18.04

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.
```
[00:03:01]>>> from auth0.v3.authentication import GetToken
[00:03:01]>>> from auth0.v3.management import Auth0
[00:03:06]>>> 
[00:03:11]>>> get_token = GetToken(domain)
[00:03:11]>>> token = get_token.client_credentials(non_interactive_client_id,
...     non_interactive_client_secret, 'https://{}/api/v2/'.format(domain))

[00:03:12]>>> mgmt_api_token = token['access_token']
[00:03:15]>>> auth0 = Auth0(domain, mgmt_api_token)  
[00:03:29]>>> auth0.users.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/users.py", line 69, in list
    return self.client.get(self._url(), params=params)
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 52, in get
    return self._process_response(response)
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 86, in _process_response
    return self._parse(response).content()
  File "/home/d33tah/virtualenv/lib/python3.6/site-packages/auth0/v3/management/rest.py", line 106, in content
    message=self._error_message())
auth0.v3.exceptions.Auth0Error: 400: You are not allowed to use search_engine=v1.
```

**Comment by d33tah** [comment]
This worked:

```
auth0.users.list(search_engine='v3')
```

Still, it would be much better for this to be default if it doesn't affect only me.

**Comment by lbalmaceda** [comment]
The default I found in the code is v1 and was deprecated a long time ago. In fact, v2 was deprecated on June and some tenants already can't make use of it. This should definitely change but I'm not sure how would that affect existing users that don't specify a version (but still have it enabled for the tenant, as they might have a really old tenant). Is it v2? v3? Maybe we shouldn't send anything so that the default is set by the server instead. I'll raise this internally and make sure this gets updated within the next weeks. 
Just to clarify, the "v3" that you see in the error message relates to this SDK's version rather than the search_engine version, which is what the server expects for the search query to work fine.

The solution you proposed is the correct path. You need to specify a `search_engine` version when calling the Users entity of the Auth0 Management API. I'll keep this open as a reminder. Thank you.

**Comment by lbalmaceda** [comment]
Default value will be removed in next version 👍
