### ISSUE TITLE
Missing jwt dependency

### ISSUE THREAD

**Issue by redbaron** [auth0/auth0-python#266]
### Describe the problem

Missing `jwt` dependency

### Reproduction

```
$ python3 -m venv /tmp/venv

$ /tmp/venv/bin/pip3 install auth0-python
Collecting auth0-python
  Downloading auth0_python-3.16.0-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 910 kB/s 
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Installing collected packages: chardet, idna, urllib3, certifi, requests, auth0-python
Successfully installed auth0-python-3.16.0 certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4

$ /tmp/venv/bin/python3 
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from auth0.v3.authentication.token_verifier import TokenVerifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/auth0/v3/authentication/token_verifier.py", line 4, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
```

### Environment

- **Version of this library used:** 3.16.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:** Ubuntu 20.04, Python 3.8

**Comment by lbalmaceda** [comment]
Thanks, I was able to reproduce this in a virtual env. I'll remove the `requirements.txt` file and use `install_requires` instead.
