### ISSUE TITLE
Retrieving an existing organisation by name fails with error

### ISSUE THREAD

**Issue by queenvictoria** [auth0/auth0-python#268]
### Describe the problem

Retrieving an existing organisation by name fails with 
```
auth0.v3.exceptions.Auth0Error: 400: Query validation error: 'Additional properties not allowed: name'.
```

### What was the expected behavior?

The function should return the requested organisation.

### Reproduction

1. Create a management app and retrieve credentials.
1. Grant management app `read_organizations` permission.
2. Create a new organisation (requires enterprise account) and store the organisation name.
3. Run the following programme.

```python
import os
from auth0.v3.authentication import GetToken
from auth0.v3.management import Auth0


domain = 'my-domain.auth0.com'

non_interactive_client_id = os.environ.get('AUTH0_MANAGEMENT_ID')
non_interactive_client_secret = os.environ.get('AUTH0_MANAGEMENT_SECRET')

get_token = GetToken(domain)
token = get_token.client_credentials(non_interactive_client_id,
    non_interactive_client_secret, 'https://{}/api/v2/'.format(domain))
token = token['access_token']
client = Auth0(domain, token)

org = self.client.organizations.get_organization_by_name('my-org')

print(org)
```

Response
```
Traceback (most recent call last):
  File "libs/auth_management.py", line 80, in <module>
    main()
  File "libs/auth_management.py", line 76, in main
    service.getOrganisation(payload)
  File "libs/auth_management.py", line 30, in getOrganisation
    org = self.client.organizations.get_organization_by_name('my-org')
  File "auth0/v3/management/organizations.py", line 63, in get_organization_by_name
    return self.client.get(self._url(), params=params)
  File "auth0/v3/management/rest.py", line 54, in get
    return self._process_response(response)
  File "auth0/v3/management/rest.py", line 88, in _process_response
    return self._parse(response).content()
  File "auth0/v3/management/rest.py", line 113, in content
    raise Auth0Error(status_code=self._status_code,
auth0.v3.exceptions.Auth0Error: 400: Query validation error: 'Additional properties not allowed: name'.
```

### Environment

- **Version of this library used:** 3.16.0
- **Which framework are you using, if applicable:** currently with a Python (3.8) module
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by lbalmaceda** [comment]
Thanks for the detailed report! I have [cross-checked with the API docs](https://auth0.com/docs/api/management/v2#!/Organizations/get_name_by_name) and I've merged your contribution.
